module Assets where

-- Trust me i did not type this by hand :)
periodicTable :: [(String, String, Integer, Double, String, String)]
periodicTable =
  [ ("H" , "Hydrogen"     , 1  , 1.00794    , "nonmetal"        , "gas")
  , ("He", "Helium"       , 2  , 4.002602   , "noble gas"       , "gas")
  , ("Li", "Lithium"      , 3  , 6.941      , "alkali metal"    , "solid")
  , ("Be", "Beryllium"    , 4  , 9.012182   , "alkaline metal"  , "solid")
  , ("B" , "Boron"        , 5  , 10.811     , "metalloid"       , "solid")
  , ("C" , "Carbon"       , 6  , 12.011     , "nonmetal"        , "solid")
  , ("N" , "Nitrogen"     , 7  , 14.00674   , "nonmetal"        , "gas")
  , ("O" , "Oxygen"       , 8  , 15.9994    , "nonmetal"        , "gas")
  , ("F" , "Fluorine"     , 9  , 18.9984032 , "nonmetal"        , "gas")
  , ("Ne", "Neon"         , 10 , 20.1797    , "noble gas"       , "gas")
  , ("Na", "Sodium"       , 11 , 22.98976928, "alkali metal"    , "solid")
  , ("Mg", "Magnesium"    , 12 , 24.305     , "alkaline metal"  , "solid")
  , ("Al", "Aluminium"    , 13 , 26.9815386 , "metal"           , "solid")
  , ("Si", "Silicon"      , 14 , 28.0855    , "metalloid"       , "solid")
  , ("P" , "Phosphorus"   , 15 , 30.973762  , "nonmetal"        , "solid")
  , ("S" , "Sulfur"       , 16 , 32.065     , "nonmetal"        , "solid")
  , ("Cl", "Chlorine"     , 17 , 35.453     , "nonmetal"        , "gas")
  , ("Ar", "Argon"        , 18 , 39.948     , "noble gas"       , "gas")
  , ("K" , "Potassium"    , 19 , 39.0983    , "alkali metal"    , "solid")
  , ("Ca", "Calcium"      , 20 , 40.078     , "alkaline metal"  , "solid")
  , ("Sc", "Scandium"     , 21 , 44.9559085 , "transition metal", "solid")
  , ("Ti", "Titanium"     , 22 , 47.867     , "transition metal", "solid")
  , ("V" , "Vanadium"     , 23 , 50.9415    , "transition metal", "solid")
  , ("Cr", "Chromium"     , 24 , 51.9961    , "transition metal", "solid")
  , ("Mn", "Manganese"    , 25 , 54.938045  , "transition metal", "solid")
  , ("Fe", "Iron"         , 26 , 55.845     , "transition metal", "solid")
  , ("Co", "Cobalt"       , 27 , 58.933195  , "transition metal", "solid")
  , ("Ni", "Nickel"       , 28 , 58.6934    , "transition metal", "solid")
  , ("Cu", "Copper"       , 29 , 63.546     , "transition metal", "solid")
  , ("Zn", "Zinc"         , 30 , 65.38      , "transition metal", "solid")
  , ("Ga", "Gallium"      , 31 , 69.723     , "metal"           , "solid")
  , ("Ge", "Germanium"    , 32 , 72.63      , "metalloid"       , "solid")
  , ("As", "Arsenic"      , 33 , 74.9216    , "metalloid"       , "solid")
  , ("Se", "Selenium"     , 34 , 78.96      , "nonmetal"        , "solid")
  , ("Br", "Bromine"      , 35 , 79.904     , "nonmetal"        , "liquid")
  , ("Kr", "Krypton"      , 36 , 83.798     , "noble gas"       , "gas")
  , ("Rb", "Rubidium"     , 37 , 85.4678    , "alkali metal"    , "solid")
  , ("Sr", "Strontium"    , 38 , 87.62      , "alkaline metal"  , "solid")
  , ("Y" , "Yttrium"      , 39 , 88.90585   , "transition metal", "solid")
  , ("Zr", "Zirconium"    , 40 , 91.224     , "transition metal", "solid")
  , ("Nb", "Niobium"      , 41 , 92.90638   , "transition metal", "solid")
  , ("Mo", "Molybdenum"   , 42 , 95.96      , "transition metal", "solid")
  , ("Tc", "Technetium"   , 43 , 98         , "transition metal", "solid")
  , ("Ru", "Ruthenium"    , 44 , 101.07     , "transition metal", "solid")
  , ("Rh", "Rhodium"      , 45 , 102.9055   , "transition metal", "solid")
  , ("Pd", "Palladium"    , 46 , 106.42     , "transition metal", "solid")
  , ("Ag", "Silver"       , 47 , 107.8682   , "transition metal", "solid")
  , ("Cd", "Cadmium"      , 48 , 112.411    , "transition metal", "solid")
  , ("In", "Indium"       , 49 , 114.818    , "metal"           , "solid")
  , ("Sn", "Tin"          , 50 , 118.71     , "metal"           , "solid")
  , ("Sb", "Antimony"     , 51 , 121.76     , "metalloid"       , "solid")
  , ("Te", "Tellurium"    , 52 , 127.6      , "metalloid"       , "solid")
  , ("I" , "Iodine"       , 53 , 126.90447  , "nonmetal"        , "solid")
  , ("Xe", "Xenon"        , 54 , 131.293    , "noble gas"       , "gas")
  , ("Cs", "Caesium"      , 55 , 132.90545  , "alkali metal"    , "solid")
  , ("Ba", "Barium"       , 56 , 137.327    , "alkaline metal"  , "solid")
  , ("La", "Lanthanum"    , 57 , 138.9055   , "lanthanide"      , "solid")
  , ("Ce", "Cerium"       , 58 , 140.116    , "lanthanide"      , "solid")
  , ("Pr", "Praseodymium" , 59 , 140.90765  , "lanthanide"      , "solid")
  , ("Nd", "Neodymium"    , 60 , 144.24     , "lanthanide"      , "solid")
  , ("Pm", "Promethium"   , 61 , 145        , "lanthanide"      , "solid")
  , ("Sm", "Samarium"     , 62 , 150.36     , "lanthanide"      , "solid")
  , ("Eu", "Europium"     , 63 , 151.964    , "lanthanide"      , "solid")
  , ("Gd", "Gadolinium"   , 64 , 157.25     , "lanthanide"      , "solid")
  , ("Tb", "Terbium"      , 65 , 158.92535  , "lanthanide"      , "solid")
  , ("Dy", "Dysprosium"   , 66 , 162.5      , "lanthanide"      , "solid")
  , ("Ho", "Holmium"      , 67 , 164.93032  , "lanthanide"      , "solid")
  , ("Er", "Erbium"       , 68 , 167.259    , "lanthanide"      , "solid")
  , ("Tm", "Thulium"      , 69 , 168.93421  , "lanthanide"      , "solid")
  , ("Yb", "Ytterbium"    , 70 , 173.054    , "lanthanide"      , "solid")
  , ("Lu", "Lutetium"     , 71 , 174.9668   , "lanthanide"      , "solid")
  , ("Hf", "Hafnium"      , 72 , 178.49     , "transition metal", "solid")
  , ("Ta", "Tantalum"     , 73 , 180.94788  , "transition metal", "solid")
  , ("W" , "Tungsten"     , 74 , 183.84     , "transition metal", "solid")
  , ("Re", "Rhenium"      , 75 , 186.207    , "transition metal", "solid")
  , ("Os", "Osmium"       , 76 , 190.23     , "transition metal", "solid")
  , ("Ir", "Iridium"      , 77 , 192.217    , "transition metal", "solid")
  , ("Pt", "Platinum"     , 78 , 195.084    , "transition metal", "solid")
  , ("Au", "Gold"         , 79 , 196.9665   , "transition metal", "solid")
  , ("Hg", "Mercury"      , 80 , 200.59     , "transition metal", "liquid")
  , ("Tl", "Thallium"     , 81 , 204.3833   , "metal"           , "solid")
  , ("Pb", "Lead"         , 82 , 207.2      , "metal"           , "solid")
  , ("Bi", "Bismuth"      , 83 , 208.9804   , "metal"           , "solid")
  , ("Po", "Polonium"     , 84 , 209        , "metalloid"       , "solid")
  , ("At", "Astatine"     , 85 , 210        , "metalloid"       , "solid")
  , ("Rn", "Radon"        , 86 , 222        , "noble gas"       , "gas")
  , ("Fr", "Francium"     , 87 , 223        , "alkali metal"    , "solid")
  , ("Ra", "Radium"       , 88 , 226        , "alkaline metal"  , "solid")
  , ("Ac", "Actinium"     , 89 , 227        , "actinide"        , "solid")
  , ("Th", "Thorium"      , 90 , 232.0377   , "actinide"        , "solid")
  , ("Pa", "Protactinium" , 91 , 231.0359   , "actinide"        , "solid")
  , ("U" , "Uranium"      , 92 , 238.0289   , "actinide"        , "solid")
  , ("Np", "Neptunium"    , 93 , 237        , "actinide"        , "solid")
  , ("Pu", "Plutonium"    , 94 , 244        , "actinide"        , "solid")
  , ("Am", "Americium"    , 95 , 243        , "actinide"        , "solid")
  , ("Cm", "Curium"       , 96 , 247        , "actinide"        , "solid")
  , ("Bk", "Berkelium"    , 97 , 247        , "actinide"        , "solid")
  , ("Cf", "Californium"  , 98 , 251        , "actinide"        , "solid")
  , ("Es", "Einsteinium"  , 99 , 252        , "actinide"        , "solid")
  , ("Fm", "Fermium"      , 100, 257        , "actinide"        , "solid")
  , ("Md", "Mendelevium"  , 101, 258        , "actinide"        , "solid")
  , ("No", "Nobelium"     , 102, 259        , "actinide"        , "solid")
  , ("Lr", "Lawrencium"   , 103, 262        , "actinide"        , "solid")
  , ("Rf", "Rutherfordium", 104, 261        , "transition metal", "solid")
  , ("Db", "Dubnium"      , 105, 262        , "transition metal", "solid")
  , ("Sg", "Seaborgium"   , 106, 266        , "transition metal", "solid")
  , ("Bh", "Bohrium"      , 107, 264        , "transition metal", "solid")
  , ("Hs", "Hassium"      , 108, 269        , "transition metal", "solid")
  , ("Mt", "Meitnerium"   , 109, 268        , "transition metal", "solid")
  , ("Ds", "Darmstadtium" , 110, 271        , "transition metal", "solid")
  , ("Rg", "Roentgenium"  , 111, 272        , "transition metal", "solid")
  , ("Cn", "Copernicium"  , 112, 285        , "transition metal", "solid")
  , ("Nh", "Nihonium"     , 113, 284        , "transition metal", "solid")
  , ("Fl", "Flerovium"    , 114, 289        , "transition metal", "solid")
  , ("Mc", "Moscovium"    , 115, 288        , "transition metal", "solid")
  , ("Lv", "Livermorium"  , 116, 293        , "transition metal", "solid")
  , ("Ts", "Tennessine"   , 117, 294        , "transition metal", "solid")
  , ("Og", "Oganesson"    , 118, 294        , "actinide"        , "solid")
  ]
